server:
  port: 8080
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  h2:
    console:
      enabled: true
  profiles:
    include: api
loggin:
  level:
    site:
      deepsleep:
        dyfawd:
          config:
            commandline: debug